ROLE_POOLS = {
    "code_generation":  ["architect", "implementation_engineer", "critic", "tester", "synthesizer"],
    "bug_fix":          ["debugger", "root_cause_analyst", "patch_engineer", "regression_tester"],
    "architecture":     ["principal_architect", "backend_engineer", "devops_engineer", "critic", "tester"],
    "security_review":  ["security_reviewer", "abuse_case_red_teamer", "defensive_fix_engineer", "secrets_reviewer"],
    "frontend_ui":      ["ux_engineer", "frontend_engineer", "accessibility_reviewer", "state_management_critic"],
    "devops":           ["devops_engineer", "reliability_critic", "deployment_engineer", "cost_reviewer"],
    "database_migration": ["schema_architect", "migration_engineer", "rollback_planner", "performance_critic"],
    "test_generation":  ["test_engineer", "edge_case_hunter", "coverage_critic"],
    "refactor":         ["refactor_engineer", "behaviour_preservation_critic", "test_engineer"],
    "documentation":    ["technical_writer", "completeness_critic", "example_engineer"],
    "debugging":        ["debugger", "root_cause_analyst", "regression_tester"],
    "explanation":      ["teacher", "completeness_critic", "example_engineer"],
    "reasoning":        ["principal_analyst", "critic", "synthesizer"],
    "general_qa":       ["generalist", "critic", "synthesizer"],
    "code_review":      ["critic", "behaviour_preservation_critic", "security_reviewer", "test_engineer"],
}

ROLE_CAPABILITY_MAP = {
    "architect": "reasoning", "principal_architect": "reasoning",
    "implementation_engineer": "coding_strength", "backend_engineer": "coding_strength",
    "frontend_engineer": "coding_strength", "patch_engineer": "coding_strength",
    "refactor_engineer": "coding_strength", "migration_engineer": "coding_strength",
    "critic": "critique", "behaviour_preservation_critic": "critique",
    "completeness_critic": "critique", "performance_critic": "critique",
    "tester": "reasoning", "regression_tester": "reasoning", "test_engineer": "reasoning",
    "security_reviewer": "critique", "abuse_case_red_teamer": "critique",
    "synthesizer": "synthesis", "debugger": "reasoning", "root_cause_analyst": "reasoning",
    "devops_engineer": "tool_use", "deployment_engineer": "tool_use",
    "cost_reviewer": "reasoning", "reliability_critic": "critique",
    "secrets_reviewer": "critique", "defensive_fix_engineer": "coding_strength",
    "ux_engineer": "reasoning", "accessibility_reviewer": "critique",
    "state_management_critic": "critique", "schema_architect": "reasoning",
    "rollback_planner": "reasoning", "edge_case_hunter": "critique",
    "technical_writer": "synthesis", "example_engineer": "coding_strength",
    "teacher": "synthesis", "principal_analyst": "reasoning",
    "generalist": "synthesis",
}

STATIC_WEIGHTS_TABLE = {
    "code_generation": {"code": .8, "reasoning": .5, "math": .1, "creative": .1, "long_context": .3, "tool_use": .2, "critique": .3},
    "bug_fix": {"code": .8, "reasoning": .7, "math": .1, "creative": .0, "long_context": .4, "tool_use": .2, "critique": .6},
    "code_review": {"code": .7, "reasoning": .7, "math": .1, "creative": .0, "long_context": .5, "tool_use": .2, "critique": .9},
    "debugging": {"code": .8, "reasoning": .8, "math": .1, "creative": .0, "long_context": .4, "tool_use": .3, "critique": .7},
    "refactor": {"code": .8, "reasoning": .6, "math": .1, "creative": .0, "long_context": .6, "tool_use": .2, "critique": .7},
    "architecture": {"code": .5, "reasoning": .9, "math": .1, "creative": .2, "long_context": .7, "tool_use": .3, "critique": .7},
    "test_generation": {"code": .7, "reasoning": .7, "math": .1, "creative": .0, "long_context": .4, "tool_use": .2, "critique": .8},
    "security_review": {"code": .7, "reasoning": .8, "math": .1, "creative": .0, "long_context": .5, "tool_use": .3, "critique": .9},
    "devops": {"code": .4, "reasoning": .7, "math": .1, "creative": .0, "long_context": .5, "tool_use": .8, "critique": .7},
    "database_migration": {"code": .6, "reasoning": .8, "math": .2, "creative": .0, "long_context": .6, "tool_use": .3, "critique": .8},
    "frontend_ui": {"code": .7, "reasoning": .5, "math": .1, "creative": .4, "long_context": .4, "tool_use": .2, "critique": .6},
    "documentation": {"code": .3, "reasoning": .5, "math": .0, "creative": .3, "long_context": .5, "tool_use": .1, "critique": .5},
    "explanation": {"code": .3, "reasoning": .6, "math": .1, "creative": .2, "long_context": .3, "tool_use": .1, "critique": .4},
    "reasoning": {"code": .1, "reasoning": .9, "math": .4, "creative": .1, "long_context": .4, "tool_use": .1, "critique": .6},
    "general_qa": {"code": .1, "reasoning": .5, "math": .1, "creative": .2, "long_context": .2, "tool_use": .1, "critique": .3},
}
